### PR TITLE
Stage lifecycle

### PR DESCRIPTION
**Pull request by johnou**
@DanielSperry something like this? You may want to repackage the lifecycle class, had a hard time trying to find it a good home.

### CODE REVIEW

**Comment by DanielSperry** [comment]
Look good :)

**Comment by DanielSperry** [comment]
But why make it mandatory?

**Comment by johnou** [comment]
I wouldn't call an interface with a default method mandatory? There are not going to be many extensions, the call is not expensive, only invoked on shutdown and it reduces boilerplate code in the extension implementation itself.

**Comment by DanielSperry** [comment]
good point :)

**Pull request merged**
