### PR TITLE
Ldap Storage Provider

### PR DESCRIPTION
**Pull request by quilombodigital**
LDAP Storage Provider
=======

###### How to use it

Adding the provider:

```java
        LdapStorageProvider provider = new LdapStorageProvider();
        provider.setHost("localhost");
        provider.setPort(10389);
        provider.setDn("uid=admin,ou=system");
        provider.setCredentials("secret");
        stage.addProvider(provider);
```

State example:

```java
@LdapEntity(
        dnKey = "uid",
        baseDn = "ou=people, dc=example, dc=com",
        attributes = {
                "ObjectClass: inetOrgPerson",
                "ObjectClass: organizationalPerson",
                "ObjectClass: top",
                "ObjectClass: person"
        })
public class LdapUserState
{

    @LdapAttribute("cn")
    public String commonName;

    @LdapAttribute("sn")
    public String surName;

    public String postalCode;

    public String userPassword;

}
```

Actor Example:

```java
public class LdapAuthenticateActor extends OrbitActor<LdapUserState> implements ILdapAuthenticateActor
{

    @Override
    public Task<Boolean> authenticate(final String password)
    {
        if (!readState().join() || state().userPassword == null)
        {
            return Task.fromValue(false);
        }
        return Task.fromValue(state().userPassword.equals(LdapStorageUtil.toPasswordHash(password)));

    }

    @Override
    public Task<Void> register(final String name, final String surname, String postalcode, final String password)
    {
        state().postalCode = postalcode;
        state().commonName = name;
        state().surName = surname;
        state().userPassword = LdapStorageUtil.toPasswordHash(password);
        writeState().join();
        return Task.done();
    }

    @Override
    public Task<Void> remove()
    {
        clearState().join();
        state().userPassword = null;
        state().commonName = null;
        state().postalCode = null;
        state().surName = null;
        return Task.done();
    }

}
```

**Note1: The user authentication example was chosen because it is the most common scenario, but different approachs can be used.**
**Note2: I used locally the ApacheDS(apacheds-2.0.0-M14) and Apache Directory Studio(2.0.0-M8) to test the provider.**

### CODE REVIEW

**Comment by JoeHegarty** [comment]
Seems there is a problem with the dependencies and the build fails.
Otherwise it looks good.

Can you resolve the below issue?

Failed to execute goal on project orbit-actors-ldap: Could not resolve dependencies for project com.ea.orbit:orbit-actors-ldap:jar:0.2.4-SNAPSHOT: Failure to find org.apache.directory.shared:apache-ldap-api:jar:1.0.0-M13

Thanks!

**Comment by quilombodigital** [comment]
I´ve fixed the maven dependency. Thanks. :)

**Comment by JoeHegarty** [comment]
Perfect, thanks. Merged

**Comment by DanielSperry** [comment]
This is very creative! Wow :)

**Comment by DanielSperry** [comment]
@quilombodigital Do you think it's possible to automate the testing of this with travis?

**Comment by quilombodigital** [comment]
I´ll check later and try to make a test, but probably needs a openldap install

**Pull request merged**
