### PR TITLE
Support for marking immutable objects to avoid cloning.

### PR DESCRIPTION
**Pull request by johnou**

### CODE REVIEW

**Comment by DanielSperry** [comment]
It's all or nothing, right?

If a single parameter is not immutable everything gets cloned together:
to avoid problems with graphs:  (immutable p1, mutable p2={a=p1})

**Comment by johnou** [comment]
Correct, but on second thought it might make more sense to extract all this immutable logic into a helper that the  cloners can use wdyt?

**Comment by johnou** [comment]
Yep or cloning would get pretty messy in my opinion.

**Comment by DanielSperry** [comment]
cool let's merge it.

**Pull request merged**
