### PR TITLE
Fixed reminder bug and introduced NoDeactivate annotation.

### PR DESCRIPTION
**Pull request by JoeHegarty**
This fixes a reported issue of reminders not always firing. It also introduces the NoDeactivate annotation which helps fix that issue.

### CODE REVIEW

**Comment by johnou** [comment]
Not a super fan of the annotation name but I cannot think of something else at the moment..

**Comment by FieldFlux** [comment]
Perhaps the annotation can be called AlwaysActive? or AlwaysActivated? I prefer Positive Logic when naming things :)

**Comment by JoeHegarty** [comment]
My only concern with "AlwaysActivated" is it suggests to me that the framework is going to activate it for you, but that's not the case. You still need to trigger the initial activation.

**Comment by FieldFlux** [comment]
Hmm, yeah, I hadn't thought of that. Maybe NeverDeactivate instead of NoDeactivate?

**Comment by JoeHegarty** [comment]
NeverDeactivate works for me.

**Comment by DanielSperry** [comment]
What happens on node shutdown/crash for NeverDeactivate actors?

**Comment by JoeHegarty** [comment]
You'll need to activate it on another node. The framework won't do anything special in that case.

**Comment by JoeHegarty** [comment]
We could name it more like PreferLocalPlacement.
Make it PreferPerpetual or PreferPermanent or similar?

**Pull request merged**
